name: rocketfly
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  flutter_rating_bar: ^4.0.0
  pin_code_fields: ^7.3.0
  flutter_svg_provider: ^1.0.3
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  grouped_list: ^5.1.2
  sms_autofill: ^2.0.0
  dotted_border: 2.0.0+3
  intl: ^0.18.0
  onboarding_animation: ^0.0.3
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoMedium.ttf
          weight: 500
        - asset: assets/fonts/LatoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: League Spartan
      fonts: 
        - asset: assets/fonts/LeagueSpartanMedium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LeagueSpartanRegular.ttf
          weight: 400
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
